# --- !Ups

create table "book" (
  "id" int generated by default as identity(start with 1) not null primary key,
  "title" varchar not null,
  "price" int not null,
  "author" varchar not null
);

insert into book values('Java',15,'wangwu');
insert into book values('C++',18,'lisi');
insert into book values('PHP',12,'zhangsan')

# --- !Downs

drop table "book" if exists;